### ISSUE TITLE
Use operationId for `parameterMethod` insted of the first parameter

### ISSUE THREAD

**Issue by arkraft** [bennyn/swaxios#56]
Swagger supports an operationId field which could be used as the generated methods name. It would be possible to control the name of the generated method.

**Comment by ffflorian** [comment]
@arkraft Thanks for the suggestion! Operation IDs are now supported in [`v0.0.19`](https://github.com/bennyn/swaxios/releases/tag/v0.0.19).

**Comment by arkraft** [comment]
That was fucking fast :sweat_smile: Thanks!
