### ISSUE TITLE
Extract types

### ISSUE THREAD

**Issue by arkraft** [bennyn/swaxios#58]
Currently, the return values of the methods are inline interfaces. This way they cannot be used to type any attributes. I would like to use the types for typing a vuex store, but would have to recreate them for this use case. It would be great if one could extract the types and reuse them in other parts of the application.

**Comment by bennyn** [comment]
Creating TypeScript interfaces from schema definitions is on our roadmap. 📑

We have a working draft here: https://github.com/bennyn/swaxios/tree/feat/interfaces

Stay tuned! 🙂

**Comment by arkraft** [comment]
That's awesome, thank you very much. I was testing client generators for swagger and this is by far the best i have tested. This is the only feature i am currently missing!

**Comment by bennyn** [comment]
Which other Swagger generators have you tested? Maybe we can get the best of both worlds!

**Comment by arkraft** [comment]
- [openapi-client-axios](https://www.npmjs.com/package/openapi-client-axios): which uses the OpenAPI v3, but i need Swagger v2 because this is the version we are automatically generating
- [swagger-taxos-codegen](https://www.npmjs.com/package/swagger-taxos-codegen): which did absolutely nothing, no files are created and no error message shown. Nothing happens, so i gave up
- [swagger-axios-codegen](https://www.npmjs.com/package/swagger-axios-codegen): this one generates only one file for the complete api which i did not like that much. Advantage of it is, that the services which are created are not solely based on the route. So just because there are subroutes, it does not split it up. I don't know how they actually determine what belongs into a service, my guess is, they use the tags of the routes.
- another one which i cannot find right now, but it only created one empty api file and one empty types file

Most of them are also old, they sometimes had no update in over a year and typescript changed a lot since then.

**Comment by ffflorian** [comment]
Hey @arkraft, I created #71 which will enable the creation of interfaces. If you like to, you can check out the branch [`feat/interfaces`](https://github.com/bennyn/swaxios/tree/feat/interfaces) and test it with some of your projects. I'd be happy to get some feedback and / or bug reports :slightly_smiling_face:

**Comment by arkraft** [comment]
Awesome, will definitely try it later!
