### ISSUE TITLE
Add repository information in package.json

### ISSUE THREAD

**Issue by arkraft** [bennyn/swaxios#59]
The repository information is currently missing in the `package.json`. Therefore npmjs.com is not linking to github. One needs to search swaxios on github to find this repository

**Comment by bennyn** [comment]
Good hint! 

I just opened a PR to address this issue: https://github.com/bennyn/swaxios/pull/60

Is it to your liking?

**Comment by arkraft** [comment]
Yes, thank you. I hope you will get more people here by doing so. Keep up the good work

**Comment by bennyn** [comment]
@arkraft We just added repository information in [v0.0.20](https://github.com/bennyn/swaxios/releases/tag/v0.0.20). 🎉

Can you tell us how you found the Swaxios project? This may help us to make more users aware of our API generator.

**Comment by arkraft** [comment]
I was looking for a generator, so i headed to github and did a search with `swagger axios typescript` and `language:typescript swagger axios` but it did not come up at first (now it does). After i was not satisfied with the results, i headed to [npmjs.com](https://npmjs.com) and did the same search. Swaxios was at the top so i looked at it further. Because there was no link to github i first thought it might be closed source and that we might not be able to use it due to the licence, so i looked further. After testing a few i came back  (still not satisfied) and tested swaxios. I then wanted to open an issue for the operationId but did not know the repo, so i did a google search for swaxios and came to github, wondering why there was no link on [npmjs.com](https://npmjs.com).

I think the tags and the link to the repo will help a lot, because like i said, i did not even test it at first because there was no github link

**Comment by bennyn** [comment]
Thanks for sharing your story with us. I added [more keywords](https://github.com/bennyn/swaxios/commit/0bd67e43882118684e7cddface5ce115b75e76f4) to our project which hopefully helps other people to discover Swaxios.
