### ISSUE TITLE
Read "consumes" and write into "headers"

### ISSUE THREAD

**Issue by bennyn** [bennyn/swaxios#64]
From the specification there can be a `consumes` property. We should read it and add it to the "headers" section within the `AxiosRequestConfig` object.

Example:

```jsonc
  "/api/v1/exchange/{id}": {
    "delete": {
      "consumes": [
        "application/json"
      ],
      // ...
  }
```

->

```ts
  const config: AxiosRequestConfig = {
    headers: { 'content-type': 'application/json' },
    // ...
  };
```

**Comment by ffflorian** [comment]
@bennyn What if `consumes` contains multiple entries?

Example:
```jsonc
  "/api/v1/exchange/{id}": {
    "delete": {
      "consumes": [
        "application/json",
        "application/xml"
      ],
      // ...
  }
```

**Comment by bennyn** [comment]
Hmm. I haven't thought of that case. If we don't set the `'content-type'`, then axios will automatically assign one. I think we should stay with this implementation until it becomes a problem.

**Comment by ffflorian** [comment]
We could use this idea to filter out paths which only consume "application/xml" since Swaxios can't handle these anyway.

**Comment by bennyn** [comment]
I think axios supports XML too so we should be good with it's auto detection mode for now. I would close this issue until it becomes a problem. WDYT?

**Comment by ffflorian** [comment]
Sounds good!

**Comment by ffflorian** [comment]
Btw, we should probably change the return type of an endpoint which returns XML to "string".
